### PR TITLE
fix(TestDeps): support go v1.16

### LINKED ISSUE #48: Please support go 1.16
`go` 1.16 or later is required to build binaries for Macs with Apple's M1 chip but Variant does not build with go 1.16.

```
$ go version
go version go1.16.3 linux/amd64
$ variant export binary cli cli
go: github.com/mumoshu/variant2@v0.37.1: missing go.sum entry; to add it:
	go mod download github.com/mumoshu/variant2
Error: command "sh -c cd /tmp/variant-atmos886148816; go build -o /localhost/CP_dev/atmos/abin /tmp/variant-atmos886148816": exit status 1
```
 If I try to fix that, it still fails, although differently
```
$ variant export go cli build
$ cd build
$ go mod download
$ go build
# github.com/mumoshu/variant2/pkg/app
/conf/go/pkg/mod/github.com/mumoshu/variant2@v0.37.1/pkg/app/app.go:611:36: cannot use TestDeps{} (type TestDeps) as type testing.testDeps in argument to testing.MainStart:
	TestDeps does not implement testing.testDeps (missing SetPanicOnExit0 method)
```

### PR DESCRIPTION
**Pull request by dudymas**
Resolves #48 

Create default stub for `func (TestDep) SetPanicOnExit0(bool)`

This was added in go 1.16

### CODE REVIEW

**Review by mumoshu — APPROVED** [review]
LGTM. Thanks for the fix!
